<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="robots" content="NONE,NOARCHIVE">
  <title>403 Forbidden</title>
  <style type="text/css">
    html * { padding:0; margin:0; }
    body * { padding:10px 20px; }
    body * * { padding:0; }
    body { font:small sans-serif; background:#eee; color:#000; }
    body>div { border-bottom:1px solid #ddd; }
    h1 { font-weight:normal; margin-bottom:.4em; }
    h1 span { font-size:60%; color:#666; font-weight:normal; }
    #info { background:#f6f6f6; }
    #info ul { margin: 0.5em 4em; }
    #info p, #summary p { padding-top:10px; }
    #summary { background: #ffc; }
    #explanation { background:#eee; border-bottom: 0px none; }
  </style>
</head>
<body>
<div id="summary">
  <h1>Forbidden <span>(403)</span></h1>
  <p>CSRF verification failed. Request aborted.</p>
</div>

<div id="info">
  <h2>Help</h2>
  <p>In general, this can occur when there is a genuine Cross Site Request Forgery, or when
    you didn't use the <code>Security</code> class correctly.
    For POST forms, you need to ensure:
  </p>
  <ul>
    <li>Your browser is accepting cookies.</li>
    <li>In the template, there is a 
    <code>
      &lt;input type="hidden" name="csrf_token" value="&lt;?= $this->csrfToken() ?&gt;"&gt;
    </code> tag inside each POST form that targets an internal URL.</li>
    <li>You are using the <code>Security</code> class in the namespace and created a <code>Security</code> object.</li>
    <li>You are using <code>csrfProtect</code> method on any action that use the 
    <code>&lt;input type="hidden" name="csrf_token" value="&lt;?= $this->csrfToken() ?&gt;"&gt;</code>
    tag, as well as those that accept the POST data.</li></li>
    <li>If you are not using <code>View</code> class to display your template, then you'll have to use 
    &lt;?= csrf_token_value() ?&gt; or &lt;?= (new Security)->getCsrfToken() ?&gt;</li>
    <li>The form has a valid CSRF token. After logging in in another browser
    tab or hitting the back button after a login, you may need to reload the
    page with the form, because the token is rotated after a login.</li>
  </ul>
</div>

  <div id="explanation">
    <p>
      You’re seeing this error because you have <code>'environment' => 'development'</code> in
      your application settings file. Change that to <code>'produnction</code>, and the application
      will display a standard 403 page.
    </p>
  </div>
</body>
</html>