<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>Page not found at <?= isset($_SERVER['PATH_INFO']) ? $_SERVER['PATH_INFO'] : '/' ?></title>
  <meta name="robots" content="NONE,NOARCHIVE">
  <style type="text/css">
    html * { padding:0; margin:0; }
    body * { padding:10px 20px; }
    body * * { padding:0; }
    body { font:small sans-serif; background:#eee; color:#000; }
    body>div { border-bottom:1px solid #ddd; }
    h1 { font-weight:normal; margin-bottom:.4em; }
    h1 span { font-size:60%; color:#666; font-weight:normal; }
    table { border:none; border-collapse: collapse; width:100%; }
    td, th { vertical-align:top; padding:2px 3px; }
    th { width:12em; text-align:right; color:#666; padding-right:.5em; }
    #info { background:#f6f6f6; }
    #info ol { margin: 0.5em 4em; }
    #info ol li { font-family: monospace; }
    #summary { background: #ffc; }
    #explanation { background:#eee; border-bottom: 0px none; }
    pre.exception_value { font-family: sans-serif; color: #575757; font-size: 1.5em; margin: 10px 0 10px 0; }
  </style>
</head>
<body>
  <div id="summary">
    <h1>Page not found <span>(404)</span></h1>
    <?php if (!empty($reason)) : ?><pre class="exception_value"><?= htmlentities($reason) ?></pre><?php endif; ?>
    <table class="meta">
      <tr>
        <th>Request Method:</th>
        <td><?= $_SERVER['REQUEST_METHOD'] ?></td>
      </tr>
      <tr>
        <th>Request URL:</th>
        <td><?= ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https://' : 'http://') . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] ?></td>
      </tr>
      <?php if (!empty($raised_by)) : ?>
      <tr>
        <th>Raised by:</th>
        <td><?= htmlentities($raised_by) ?></td>
      </tr>
      <?php endif; ?>
    </table>
  </div>
  <div id="info">
    <?php if (!empty($routes)) : ?>
      <p>
      Using the routes defined in <code><?= '/src/config/routes.php' ?></code>,
      the application tried these URL patterns, in this order:
      </p>
      <ol>
        <?php foreach ($routes as $route) : ?>
          <li>
            <?= htmlentities($route[1]) ?>
          </li>
        <?php endforeach; ?>
      </ol>
      <p>
        <?php if (isset($_SERVER['REQUEST_URI'])) : ?>
          The current path, <code><?= $_SERVER['REQUEST_URI'] ?></code>,
        <?php else : ?>
          The empty path
        <?php endif; ?>
        <?php if ($resolved) : ?>matched the last one.<?php else : ?>didn’t match any of these.<?php endif; ?>
      </p>
    <?php endif; ?>
  </div>

  <div id="explanation">
    <p>
      You’re seeing this error because you have <code>'environment' => 'development'</code> in
      your application settings file. Change that to <code>'produnction</code>, and the application
      will display a standard 404 page.
    </p>
  </div>
</body>
</html>