<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>Page not found at <?= isset($_SERVER['PATH_INFO']) ? $_SERVER['PATH_INFO'] : '/' ?></title>
  <meta name="robots" content="NONE,NOARCHIVE">
  <style type="text/css">
    html * { padding:0; margin:0; }
    body * { padding:10px 20px; }
    body * * { padding:0; }
    body { font:small sans-serif; background:#eee; color:#000; }
    body>div { border-bottom:1px solid #ddd; }
    h1 { font-weight:normal; margin-bottom:.4em; }
    h1 span { font-size:60%; color:#666; font-weight:normal; }
    table { border:none; border-collapse: collapse; width:100%; }
    td, th { vertical-align:top; padding:2px 3px; }
    th { width:12em; text-align:right; color:#666; padding-right:.5em; }
    #info { background:#f6f6f6; }
    #summary { background: #ffc; }
    #explanation { background:#eee; border-bottom: 0px none; }
  </style>
</head>
<body>
  <div id="summary">
    <h1>Method Not Allowed <span>(405)</span></h1>
    <table class="meta">
      <tr>
        <th>Request Method:</th>
        <td><?= $_SERVER['REQUEST_METHOD'] ?></td>
      </tr>
      <tr>
        <th>Request URL:</th>
        <td><?= ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https://' : 'http://') . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] ?></td>
      </tr>
    </table>
  </div>
  <div id="info">
    <p>
      The requested method <code><?= $_SERVER['REQUEST_METHOD'] ?></code> 
      is not allowed for the URL <code><?= $_SERVER['REQUEST_URI'] ?></code>
    </p>
  </div>

  <div id="explanation">
    <p>
      You’re seeing this error because you have <code>'environment' => 'development'</code> in
      your application settings file. Change that to <code>'produnction</code>, and the application
      will display a standard 404 page.
    </p>
  </div>
</body>
</html>