<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="robot" content="none, noarchive">
        <title><?= isset($exception_type) ? $exception_type : 'Report' ?> at <?= isset($_SERVER['PATH_INFO']) ? $_SERVER['PATH_INFO'] : '/' ?></title>
        <style>
            html * { padding:0; margin:0; }
            body * { padding:10px 20px; }
            body * * { padding:0; }
            body { font:small sans-serif; background-color:#fff; color:#000; }
            body>div { border-bottom:1px solid #ddd; }
            h1 { font-weight:normal; }
            h2 { margin-bottom:.8em; }
            h3 { margin:1em 0 .5em 0; }
            h4 { margin:0 0 .5em 0; font-weight: normal; }
            code, pre { font-size: 100%; white-space: pre-wrap; word-break: break-word; }
            summary { cursor: pointer; }
            table { border:1px solid #ccc; border-collapse: collapse; width:100%; background:white; }
            tbody td, tbody th { vertical-align:top; padding:2px 3px; }
            thead th {
            padding:1px 6px 1px 3px; background:#fefefe; text-align:left;
            font-weight:normal; font-size:11px; border:1px solid #ddd;
            }
            tbody th { width:12em; text-align:right; color:#666; padding-right:.5em; }
            table.vars { margin:5px 10px 2px 40px; width: auto; }
            table.vars td, table.req td { font-family:monospace; }
            table td.code { width:100%; }
            table td.code pre { overflow:hidden; }
            table.source th { color:#666; }
            table.source td { font-family:monospace; white-space:pre; border-bottom:1px solid #eee; }
            ul.traceback { list-style-type:none; color: #222; }
            ul.traceback li.cause { word-break: break-word; }
            ul.traceback li.frame { padding-bottom:1em; color:#4f4f4f; }
            ul.traceback li.user { background-color:#e0e0e0; color:#000 }
            div.context { padding:10px 0; overflow:hidden; }
            div.context ol { padding-left:30px; margin:0 10px; list-style-position: inside; }
            div.context ol li { font-family:monospace; white-space:pre; color:#777; cursor:pointer; padding-left: 2px; }
            div.context ol li pre { display:inline; }
            div.context ol.context-line li { color:#464646; background-color:#dfdfdf; padding: 3px 2px; }
            div.context ol.context-line li span { position:absolute; right:32px; }
            .user div.context ol.context-line li { background-color:#bbb; color:#000; }
            .user div.context ol li { color:#666; }
            div.commands, summary.commands { margin-left: 40px; }
            div.commands a, summary.commands { color:#555; text-decoration:none; }
            .user div.commands a { color: black; }
            #summary { background: #ffc; }
            #summary h2 { font-weight: normal; color: #666; }
            #explanation { background:#eee; }
            #template, #template-not-exist { background:#f6f6f6; }
            #template-not-exist ul { margin: 0 0 10px 20px; }
            #template-not-exist .postmortem-section { margin-bottom: 3px; }
            #unicode-hint { background:#eee; }
            #traceback { background:#eee; }
            #requestinfo { background:#f6f6f6; padding-left:120px; }
            #summary table { border:none; background:transparent; }
            #requestinfo h2, #requestinfo h3 { position:relative; margin-left:-100px; }
            #requestinfo h3 { margin-bottom:-1em; }
            .error { background: #ffc; }
            .specific { color:#cc3300; font-weight:bold; }
            h2 span.commands { font-size:.7em; font-weight:normal; }
            span.commands a:link {color:#5E5694;}
            pre.exception_value { font-family: sans-serif; color: #575757; font-size: 1.5em; margin: 10px 0 10px 0; }
            .append-bottom { margin-bottom: 10px; }
            .fname { user-select: all; }
        </style>
    </head>
    <body>
        <div id="summary">
            <h1><?= isset($exception_type) ? $exception_type : 'Report' ?> at <?= isset($_SERVER['PATH_INFO']) ? $_SERVER['PATH_INFO'] : '/' ?></h1>
            <pre class="exception_value"><?= $exception->getMessage() ?></pre>
            <table>
                <tbody>
                    <tr>
                        <th>Request Method:</th>
                        <td><?= $_SERVER['REQUEST_METHOD'] ?></td>
                    </tr>
                    <tr>
                        <th>Request URL:</th>
                        <td><?= ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https://' : 'http://') . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] ?></td>
                    </tr>
                    <tr>
                        <th>Framework Version:</th>
                        <td><?= FRAMEWORK_VERSION ?></td>
                    </tr>
                    <tr>
                        <th>Exception Value:</th>
                        <td><pre><?= htmlentities($exception->getMessage()) ?></pre></td>
                    </tr>
                    <tr>
                        <th>Exception Location:</th>
                        <td><span class="fname"><?= $exception->getFile() ?></span>, line <?= $exception->getLine() ?></td>
                    </tr>
                    <tr>
                        <th>Exception Code:</th>
                        <td><?= $exception->getCode() ?></td>
                    </tr>
                    <tr>
                        <th>PHP Executable:</th>
                        <td><?= PHP_BINARY ?></td>
                    </tr>
                    <tr>
                        <th>PHP Version:</th>
                        <td><?= PHP_VERSION ?></td>
                    </tr>
                    <tr>
                        <th>Operating System:</th>
                        <td><?= PHP_OS ?></td>
                    </tr>
                    <tr>
                        <th>Server time:</th>
                        <td><?= (new DateTime())->format(DateTime::RSS) ?></td>
                    </tr>
                </tbody>
            </table>
        </div>

        <?php if ($source) : ?>
        <div id="template">
            <h2>Error Source</h2>
            <p>In file <code><?= $source->file ?></code>, error at line <strong><?= $source->line ?></strong></p>
            <h3><?= htmlentities($source->message) ?></h3>
            <table class="source">
                <?php foreach ($source->lines as $source_line) : ?>
                <?php if ($source_line[0] == $source->line) : ?>
                <tr class="error">
                    <th><?= $source_line[0] ?></th>
                    <td><span class="specific"><?= htmlentities($source_line[1]) ?></span></td>
                </tr>
                <?php else : ?>
                <tr>
                    <th><?= $source_line[0] ?></th>
                    <td><?= htmlentities($source_line[1]) ?></td>
                </tr>
                <?php endif; ?>
                <?php endforeach; ?>
            </table>
        </div>
        <?php endif; ?>

        <!-- start traceback -->
        <?php if ($traceback) : ?>
        <div id="traceback">
            <h2>Traceback</h2>
            <div id="browserTraceback">
                <ul class="traceback">
                    <?php foreach ($traceback as $i => $frame) : ?>
                    <li class="frame">
                        <code class="fname"><?= isset($frame['file']) ? $frame['file'] : '&lt;unknown file&gt;' ?></code>,
                        line <?= isset($frame['line']) ? $frame['line'] : '&lt;unknown line&gt;' ?>, 
                        in <?= (isset($frame['class']) ? $frame['class'] . $frame['type'] : '') . $frame['function'] . '()' ?>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
        <?php endif; ?>
        <!-- end traceback -->

        <div id="requestinfo">
            <h2>Request information</h2>

            <h3 id="get-info">GET</h3>
            <?php if($_GET) : ?>
                <table class="req">
                    <thead>
                        <tr>
                            <th>Variable</th>
                            <th>Value</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($_GET as $k => $v) : ?>
                        <tr>
                            <td><?= $k ?></td>
                            <td class="code"><pre><?= htmlentities($v) ?></pre></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            <?php else : ?>
                <p>No GET data</p>
            <?php endif; ?>

            <h3 id="post-info">POST</h3>
            <?php if ($_POST) : ?>
                <table class="req">
                    <thead>
                        <tr>
                            <th>Variable</th>
                            <th>Value</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($_POST as $k => $v) : ?>
                        <tr>
                            <td><?= $k ?></td>
                            <td class="code"><pre><?= htmlentities($v) ?></pre></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            <?php else : ?>
                <p>No POST data</p>
            <?php endif; ?>

            <h3 id="files-info">FILES</h3>
            <?php if ($_FILES) : ?>
                <table class="req">
                    <thead>
                        <tr>
                            <th>Variable</th>
                            <th>Value</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($_FILES as $k => $v) : ?>
                            <tr>
                                <td><?= $k ?></td>
                                <td class="code"><pre><?= htmlentities($v) ?></pre></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            <?php else : ?>
                <p>No FILES data</p>
            <?php endif; ?>


            <h3 id="cookie-info">COOKIES</h3>
            <?php if ($_COOKIE) : ?>
                <table class="req">
                <thead>
                    <tr>
                    <th>Variable</th>
                    <th>Value</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($_COOKIE as $k => $v) : ?>
                    <tr>
                        <td><?= $k ?></td>
                        <td class="code"><pre><?= htmlentities($v) ?></pre></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
                </table>
            <?php else : ?>
                <p>No cookie data</p>
            <?php endif; ?>

        </div>

        <div id="explanation">
            <p>
            You’re seeing this error because you have <code>'environment' => 'development'</code> 
            in your framework settings file. Change that to <code>'production'</code>, and the application will
            display a standard page generated by the handler for this status code.
            </p>
        </div>

    </body>
</html>