<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page not found</title>
    <style>
        * {
            box-sizing: border-box;
        }
        html {
            height: 100%;
        }
        body {
            color: #555;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            background-color: #efefef;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100%;
            margin: 0;
            padding: 1rem;
        }
        h1 {
            font-size: 1.75em;
            font-weight: 400;
        }
    </style>
</head>
<body>
    <h1>404 | Page not found</h1>
</body>
</html>
