<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>The install worked successfully! Congratulations!</title>
        <style>
            :root {
                --text-color: #555;
                --primary-color: #4f7e88;
                --border-color: #efefef;
                --font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
                
            }

            body {
                max-width: 960px;
                margin: 0 auto;
                color: var(--text-color);
                font-family: var(--font-family);
                line-height: 1.15;
            }
            
            a {
                color: var(--primary-color);
            }

            h1, h2, h3, h4, h5, p, ul {
                padding: 0;
                margin: 0;
                font-weight: 400;
            }

            main {
                text-align: center;
            }
            
            header {
                display: flex;
                align-items: flex-end;
                justify-content: space-between;
                flex-wrap: wrap;
                row-gap: 8px;
                padding-top: 20px;
                padding-bottom: 10px;
                border-bottom: 1px solid var(--border-color);
            }

            .logo {
                font-weight: 700;
                font-size: 1.375rem;
                text-decoration: none;
            }

            .hero {
                color: var(--primary-color);
                margin-top: 20vh;
                margin-bottom: 2rem;
                font-size: 2.1rem;
                font-weight: 500;
            }
            
            main h1 {
                font-size: 1.375rem;
                max-width: 34rem;
                margin: 5px auto 0;
            }

            main p {
                line-height: 1.25;
                max-width: 25rem;
                margin: 15px auto 0;
            }
            
            @media (max-width: 996px) {
                body { max-width: 780px; }
            }

            @media (max-width: 800px) {
                main { padding: 0 25px; }
                main h1 { font-size: 1.25rem; }
                header { padding: 20px 20px 10px; }
                header * { flex: 1 0 100%;}
            }
          
        </style>
    </head>
    <body>
        <header>
            <a class="logo" href="#" target="_blank" rel="noopener">
            phplix
            </a>
            <p>
                View Phplix@v<?= FRAMEWORK_VERSION ?> on 
                <a href="https://github.com/mkcdr/phplix" target="_blank" rel="noopener">
                    Github
                    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" 
                    style="position: relative; top: 1px; width: 1rem; height: 1rem;" 
                    fill="none" stroke="currentColor" stroke-width="2" 
                    stroke-linecap="round" stroke-linejoin="round">
                        <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"></path>
                        <polyline points="15 3 21 3 21 9"></polyline>
                        <line x1="10" y1="14" x2="21" y2="3"></line>
                    </svg>
                </a>
            </p>
      </header>
      <main>
        <div class="hero">Phplix@v<?= FRAMEWORK_VERSION ?></div>
        <h1>The install worked successfully! Congratulations!</h1>
        <p>Welcome to your new application, you are seeing this page because this is the default URL that have been configured for you in your <code>routes.php</code> file.</p>
      </main>
    </body>
</html>
<?php $this->printExecutionTime() ?>
